/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    IconCustomVue: typeof import('~icons/custom/vue')['default']
    IconRiEBike2Fill: typeof import('~icons/ri/e-bike2-fill')['default']
  }
}
